# Generated by Django 2.1.1 on 2019-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
