# Generated by Django 2.1.3 on 2019-01-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_auto_20190128_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='token1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='token2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
