# Generated by Django 2.1.3 on 2019-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0004_auto_20190129_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default=1, max_length=1001),
            preserve_default=False,
        ),
    ]
