# Generated by Django 2.1.1 on 2019-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_myuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
