# Generated by Django 2.1.5 on 2019-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0006_auto_20190129_2156'),
        ('EventApp', '0006_myuser_user_phone'),
    ]

    operations = [
    ]
