# Generated by Django 2.1.1 on 2019-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0008_eventmaster_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='timings',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
