# Generated by Django 2.1.1 on 2019-01-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0013_auto_20190131_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EventApp.Team'),
        ),
    ]
