# Generated by Django 2.1.1 on 2019-02-01 15:32

import EventApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0014_auto_20190201_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to=EventApp.models.QRcode_path),
        ),
        migrations.AddField(
            model_name='category_assign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.Role_category'),
        ),
        migrations.AddField(
            model_name='category_assign',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.RoleMaster'),
        ),
    ]
