# Generated by Django 2.2a1 on 2019-02-09 15:31

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0020_filedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='document',
            field=models.FileField(upload_to=EventApp.models.filePath),
        ),
    ]
