# Generated by Django 2.2a1 on 2019-02-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0021_auto_20190209_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='fname',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
