# Generated by Django 2.2a1 on 2019-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0022_filedocument_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='fname',
            field=models.CharField(max_length=250),
        ),
    ]
