# Generated by Django 2.1.1 on 2019-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0023_auto_20190209_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
