# Generated by Django 2.1.1 on 2019-02-10 16:21

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0024_eventmaster_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='rules_file',
            field=models.FileField(blank=True, upload_to=EventApp.models.rules_path),
        ),
    ]
