# Generated by Django 2.1.1 on 2019-02-10 16:27

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0025_eventmaster_rules_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='rules_file',
            field=models.FileField(blank=True, default=None, upload_to=EventApp.models.rules_path),
        ),
    ]
