# Generated by Django 2.1.1 on 2019-02-11 15:52

import EventApp.models
import EventApp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0027_instamojocredential_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root',
                                               to=settings.AUTH_USER_MODEL)),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subordinate',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='document',
            field=models.FileField(upload_to=EventApp.models.filePath,
                                   validators=[EventApp.validators.validate_file_size]),
        ),
    ]
