# Generated by Django 2.1.5 on 2019-02-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0028_auto_20190211_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EventApp.EventMaster'),
        ),
    ]
