# Generated by Django 2.1.5 on 2019-02-12 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0028_auto_20190211_1517'),
        ('EventApp', '0029_roleassignment_event'),
    ]

    operations = [
    ]
