# Generated by Django 2.1.1 on 2019-01-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0029_auto_20190127_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document_type',
            options={'ordering': ['type']},
        ),
    ]
