# Generated by Django 2.1.1 on 2019-01-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0030_auto_20190127_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['category', 'title']},
        ),
    ]
