# Generated by Django 2.1.5 on 2019-02-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0030_merge_20190212_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='container_src',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
