# Generated by Django 2.1.5 on 2019-02-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0031_auto_20190212_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='container_src',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
    ]
