# Generated by Django 2.1.5 on 2019-02-12 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0032_auto_20190212_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instamojocredential',
            old_name='redirect_url',
            new_name='payment_url',
        ),
    ]
