# Generated by Django 2.1.1 on 2019-01-28 07:18

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0032_auto_20190127_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='coll_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='prof_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to=EventApp.models.path),
        ),
    ]
