# Generated by Django 2.1.3 on 2019-01-28 10:12

import EventApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0033_auto_20190128_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('file', models.FileField(upload_to=EventApp.models.path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.Document_type')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RemoveField(
            model_name='documents',
            name='category',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
