# Generated by Django 2.1.5 on 2019-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0033_auto_20190212_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instamojocredential',
            name='payment_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
