# Generated by Django 2.1.5 on 2019-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0034_auto_20190212_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
            ],
        ),
    ]
