# Generated by Django 2.1.5 on 2019-02-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0035_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.Domain'),
        ),
    ]
