# Generated by Django 2.1.1 on 2019-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0035_auto_20190128_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
