# Generated by Django 2.1.1 on 2019-02-13 07:44

import EventApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0036_auto_20190212_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='images',
            field=models.ImageField(blank=True, upload_to=EventApp.models.carousel_path),
        ),
        migrations.AlterField(
            model_name='eventdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.Department'),
        ),
    ]
