# Generated by Django 2.1.1 on 2019-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0038_auto_20190213_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='images',
            field=models.ImageField(blank=True, upload_to='Carousel_images/'),
        ),
    ]
