# Generated by Django 2.1.1 on 2019-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0041_sponsormaster_sponsor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(max_length=2000)),
                ('policy', models.TextField(max_length=2000)),
            ],
        ),
    ]
