# Generated by Django 2.1.1 on 2019-02-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0042_termsconditons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='img',
        ),
    ]
