# Generated by Django 2.1.1 on 2019-02-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0046_socialmedia_cls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='banner_src',
        ),
    ]
