# Generated by Django 2.1.1 on 2019-02-13 11:57

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0047_remove_department_banner_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='banner_src',
            field=models.ImageField(blank=True, upload_to=EventApp.models.department_path),
        ),
    ]
