# Generated by Django 2.1.1 on 2019-02-13 12:02

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0048_department_banner_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='banner_src',
            field=models.ImageField(blank=True, upload_to=EventApp.models.departmentbanner_path),
        ),
    ]
