# Generated by Django 2.1.5 on 2019-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0049_auto_20190213_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
