# Generated by Django 2.1.5 on 2019-02-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0050_auto_20190214_1017'),
        ('EventApp', '0050_eventmaster_prize'),
    ]

    operations = [
    ]
