# Generated by Django 2.1.1 on 2019-02-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0050_eventmaster_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='assigned_work',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
