# Generated by Django 2.1.5 on 2019-02-14 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0051_rolemaster_assigned_work'),
        ('EventApp', '0051_merge_20190214_1028'),
    ]

    operations = [
    ]
