# Generated by Django 2.1.5 on 2019-02-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0052_merge_20190214_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='rank',
        ),
    ]
