# Generated by Django 2.1.5 on 2019-02-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0053_remove_department_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
