# Generated by Django 2.1.5 on 2019-02-16 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0054_department_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='rank',
            new_name='rank1fg',
        ),
    ]
