# Generated by Django 2.1.1 on 2019-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0055_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='post',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
