# Generated by Django 2.1.5 on 2019-02-16 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0056_auto_20190216_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descriptionfg',
            new_name='description',
        ),
    ]
