# Generated by Django 2.1.5 on 2019-02-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0056_ourteam_post'),
        ('EventApp', '0057_auto_20190216_1220'),
    ]

    operations = [
    ]
