# Generated by Django 2.1.1 on 2019-02-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0058_merge_20190218_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleassignment',
            options={'ordering': ['role']},
        ),
        migrations.AlterModelOptions(
            name='rolemaster',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='EventApp.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='assignsub',
            unique_together={('rootuser', 'subuser')},
        ),
    ]
