# Generated by Django 2.1.1 on 2019-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0060_auto_20190219_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
