# Generated by Django 2.1.1 on 2019-02-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0059_auto_20190219_1824'),
        ('EventApp', '0061_myuser_level'),
    ]

    operations = [
    ]
