# Generated by Django 2.1.5 on 2019-02-19 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0060_auto_20190219_2220'),
        ('EventApp', '0062_merge_20190219_2000'),
    ]

    operations = [
    ]
