# Generated by Django 2.1.5 on 2019-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0063_merge_20190220_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormaster',
            name='sponsor_link',
            field=models.URLField(blank=True),
        ),
    ]
