# Generated by Django 2.1.5 on 2019-02-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0064_sponsormaster_sponsor_link'),
        ('EventApp', '0063_merge_20190219_2255'),
    ]

    operations = [
    ]
