# Generated by Django 2.1.1 on 2019-02-20 13:07

import EventApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0066_sponsormaster_sponsor_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pariwartan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to=EventApp.models.pariwartan)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
