# Generated by Django 2.1.5 on 2019-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EventApp', '0067_pariwartan'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='can_register',
            field=models.BooleanField(default=True),
        ),
    ]
