# Generated by Django 2.1.5 on 2019-02-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0065_merge_20190220_1142'),
        ('EventApp', '0068_eventmaster_can_register'),
    ]

    operations = [
    ]
