# Generated by Django 2.1.5 on 2019-02-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0069_merge_20190221_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaster',
            name='head',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='jt_head',
        ),
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_category', models.CharField(max_length=30)),
                ('category_rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sponsormaster',
            name='sponsor_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='EventApp.SponsorCategory'),
        ),
    ]
