# Generated by Django 2.1.5 on 2019-02-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0069_merge_20190221_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaster',
            name='head',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='jt_head',
        ),
    ]
