# Generated by Django 2.1.1 on 2019-02-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0070_auto_20190222_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_category', models.CharField(max_length=30)),
                ('category_rank', models.IntegerField()),
            ],
        ),
    ]
