# Generated by Django 2.1.1 on 2019-02-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0070_auto_20190222_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='insta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
