# Generated by Django 2.1.1 on 2019-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0071_auto_20190224_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='roleassignment',
            options={},
        ),
        migrations.AddField(
            model_name='team',
            name='ispresent',
            field=models.BooleanField(default=False),
        ),
    ]
