# Generated by Django 2.1.1 on 2019-02-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0071_auto_20190224_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleassignment',
            options={},
        ),
    ]
