# Generated by Django 2.1.1 on 2019-02-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0071_sponsorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormaster',
            name='sponsor_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='EventApp.SponsorCategory'),
        ),
    ]
