# Generated by Django 2.1.1 on 2019-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0072_auto_20190225_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ispresent',
            field=models.BooleanField(default=False),
        ),
    ]
