# Generated by Django 2.1.5 on 2019-02-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0073_team_ispresent'),
        ('EventApp', '0073_auto_20190225_1824'),
    ]

    operations = [
    ]
